apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: sza
  annotations:
    networking.istio.io/service-type: NodePort
spec:
  gatewayClassName: istio
  listeners:
  - name: http
    port: 80
    protocol: HTTP
    allowedRoutes:
      namespaces:
        from: Same
